#!/bin/bash

echo ""
echo "🔍 Diagnóstico Completo do Problema de Email"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. Verificar username do Resend no Supabase
echo "📋 DIAGNÓSTICO #1: Username do SMTP"
echo "   No screenshot você mostrou: 'localcashback'"
echo "   ⚠️  PROBLEMA: O username do Resend deve ser 'resend'"
echo "   ❌ Username 'localcashback' está INCORRETO"
echo ""
echo "   ✅ CORREÇÃO:"
echo "      Username: resend"
echo "      Password: <sua API Key do Resend (começa com re_)>"
echo ""

# 2. Verificar se a API key do Resend é válida
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 DIAGNÓSTICO #2: API Key do Resend"
echo ""
echo "   A API key do Resend deve:"
echo "   ✅ Começar com 're_'"
echo "   ✅ Ter permissões de 'Sending Access'"
echo "   ✅ Estar ativa (não revogada)"
echo ""

# 3. Verificar domínio verificado
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 DIAGNÓSTICO #3: Domínio Verificado no Resend"
echo ""
echo "   ⚠️  IMPORTANTE: O Resend precisa de um domínio verificado"
echo ""
echo "   Opções:"
echo "   A) Usar domínio onboarding (teste - 100 emails/dia):"
echo "      From: onboarding@resend.dev"
echo ""
echo "   B) Adicionar seu domínio:"
echo "      1. Ir em Resend Dashboard > Domains"
echo "      2. Adicionar seu domínio (ex: localcashback.com)"
echo "      3. Adicionar registros DNS (SPF, DKIM, DMARC)"
echo "      4. Aguardar verificação"
echo ""

# 4. Mostrar configuração correta
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ CONFIGURAÇÃO CORRETA NO SUPABASE:"
echo ""
echo "   Host: smtp.resend.com"
echo "   Port: 587"
echo "   Username: resend"
echo "   Password: re_xxxxxxxxxxxxxxxxxxxxx"
echo "   Sender Name: LocalCashback"
echo "   Sender Email: onboarding@resend.dev"
echo ""
echo "   (Ou use seu domínio verificado no Sender Email)"
echo ""

# 5. Verificar outra possibilidade: Email template
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 DIAGNÓSTICO #4: Email Templates do Supabase"
echo ""
echo "   Verifique se os templates de email estão configurados:"
echo "   Supabase Dashboard > Authentication > Email Templates"
echo ""
echo "   Template necessário:"
echo "   - Reset Password (Magic Link)"
echo ""

# 6. Alternativa: Usar SendGrid
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 ALTERNATIVA: Usar SendGrid (mais simples)"
echo ""
echo "   SendGrid é mais fácil de configurar:"
echo ""
echo "   1. Criar conta: https://signup.sendgrid.com/"
echo "   2. Criar API Key (Settings > API Keys)"
echo "   3. Configurar no Supabase:"
echo "      Host: smtp.sendgrid.net"
echo "      Port: 587"
echo "      Username: apikey"
echo "      Password: SG.xxxxxxxxxxxxxxxxxxxxx"
echo "      Sender: seu-email@gmail.com (verificado)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 AÇÃO IMEDIATA RECOMENDADA:"
echo ""
echo "   OPÇÃO 1 - Corrigir Resend (se quiser continuar):"
echo "   1. Voltar no Supabase > Authentication > SMTP"
echo "   2. Trocar Username de 'localcashback' para 'resend'"
echo "   3. Verificar se a senha é sua API Key válida"
echo "   4. Trocar Sender Email para 'onboarding@resend.dev'"
echo "   5. Salvar e aguardar 2 minutos"
echo "   6. Testar novamente"
echo ""
echo "   OPÇÃO 2 - Usar SendGrid (mais rápido):"
echo "   1. Criar conta SendGrid"
echo "   2. Criar API Key"
echo "   3. Configurar no Supabase conforme acima"
echo "   4. Testar"
echo ""
