#!/bin/bash
echo "=== Verificando instalação no VPS ==="
echo ""
echo "Execute estes comandos no SSH do servidor:"
echo ""
echo "# 1. Verificar se a pasta dist existe:"
echo "ls -la /var/www/cashback/cashback-system/dist"
echo ""
echo "# 2. Se não existir, buildar novamente:"
echo "cd /var/www/cashback/cashback-system && npm run build"
echo ""
echo "# 3. Verificar configuração do Nginx:"
echo "cat /etc/nginx/sites-available/localcashback"
echo ""
echo "# 4. Testar configuração Nginx:"
echo "nginx -t"
echo ""
echo "# 5. Ver logs de erro:"
echo "tail -30 /var/log/nginx/error.log"
