#!/bin/bash
# Script para atualizar o site no servidor VPS

echo "======================================"
echo "🔄 Atualizando Site no Servidor VPS"
echo "======================================"
echo ""

echo "📋 Execute estes comandos no SSH do servidor (31.97.167.88):"
echo ""
echo "ssh root@31.97.167.88"
echo ""
echo "# 1. Ir para o diretório do projeto"
echo "cd /var/www/cashback/cashback-system"
echo ""
echo "# 2. Fazer pull das últimas mudanças"
echo "git pull origin main"
echo ""
echo "# 3. Instalar dependências (se houver novas)"
echo "npm install"
echo ""
echo "# 4. Buildar a aplicação"
echo "npm run build"
echo ""
echo "# 5. Reiniciar Nginx"
echo "systemctl reload nginx"
echo ""
echo "✅ Site atualizado!"
echo ""
