#!/bin/bash

TOKEN=$(grep github.com ~/.git-credentials | sed 's/.*:\/\/.*:\(.*\)@.*/\1/')

curl -X PATCH \
  -H "Authorization: token $TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/RaulRicco/CashBack/pulls/1 \
  -d '{
    "body": "## 🎉 Mudanças Implementadas\n\n### ✅ Upload de Logo Funcionando\n- Corrigido erro de RLS no Supabase Storage\n- Bucket `merchant-assets` configurado como público\n- Upload de logo testado e funcionando perfeitamente\n- Validação de tipo de arquivo (PNG, JPG) e tamanho (máximo 2MB)\n\n### ✅ Melhorias de Interface\n- Menu renomeado: **White Label** → **Meu CashBack** ✨\n- Layout da área de upload **completamente redesenhado** e alinhado 🎨\n- Preview de logo centralizado e mais intuitivo\n- Ícone de upload em círculo colorido\n- Background cinza suave para melhor contraste\n- Texto \"Selecionar Logo\" mais destacado e visível\n- Elementos perfeitamente centralizados\n- Status de upload destacado com feedback visual\n\n### ✅ Página de Configurações White Label\n- Upload e preview de logo\n- Configuração de 3 cores (primária, secundária, destaque)\n- Preview das cores em botões de exemplo\n- Configuração de porcentagem de cashback\n- Informações do estabelecimento (nome, email, telefone)\n- Salvamento automático no banco de dados\n\n### 📋 Arquivos Modificados\n- `src/components/DashboardLayout.jsx` - Nome do menu atualizado\n- `src/pages/WhiteLabelSettings.jsx` - Layout melhorado, alinhado e funcional\n- Scripts SQL de diagnóstico e correção criados\n\n### 🔧 Configurações Técnicas\n- Bucket Supabase Storage configurado\n- Políticas RLS ajustadas\n- Integração com Supabase Storage completa\n\n### 🎯 Próximos Passos (Futuras PRs)\n1. Aplicar branding dinâmico sistema-wide\n2. Completar isolamento multi-tenant\n3. Aplicar cores personalizadas em todo o sistema\n4. Mostrar logo do merchant em páginas customer-facing\n\n### ✅ Testado\n- ✅ Upload de logo funciona\n- ✅ Preview de logo funciona\n- ✅ Salvamento de configurações funciona\n- ✅ Interface responsiva e **perfeitamente alinhada**\n- ✅ Menu lateral mostra \"Meu CashBack\" corretamente\n\n### 📝 Commits\n- `507576b` - fix(ui): alterar White Label para Meu CashBack e melhorar layout\n- `3547610` - fix(storage): corrigir upload de logo tornando bucket público\n- `1838aba` - fix(ui): melhorar alinhamento da área de upload de logo\n\n---\n\n**Review**: Pronto para merge! 🚀\n\n**Total de commits:** 3\n**Arquivos alterados:** 13"
  }'
